name: Build Pyodide & Deploy to GitHub Pages  # 可修改名称，明确工作流功能
on:
  push:
    branches: [ main ]  # 保留原有触发条件
jobs:
  build-and-deploy:  # 可修改job名称，体现“构建+部署”
    runs-on: ubuntu-latest  # 保留原有运行环境
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4  # 保留原有拉取步骤
      
  - name: Build Custom Pyodide
  uses: jobovy/pyodide-buildpackage-action@v1.0.0
  with:
    # 原 'pyodide-version' 改为 'pyodide-tag'（用标签指定版本，如 0.25.0）
    pyodide-tag: 0.25.0  
    # 原 'packages' 需写进 meta.yaml 文件，通过 'meta-yaml-path' 引用
    meta-yaml-path: './pyodide_meta.yaml'  
    output-dir: './dist/static/pyodide'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 部署目录包含新增的Pyodide资