name: Build Pyodide & Deploy to GitHub Pages  # 可修改名称，明确工作流功能
on:
  push:
    branches: [ main ]  # 保留原有触发条件
jobs:
  build-and-deploy:  # 可修改job名称，体现“构建+部署”
    runs-on: ubuntu-latest  # 保留原有运行环境
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4  # 保留原有拉取步骤
      
      # 新增：Pyodide构建步骤（核心新增内容）
      - name: 定制化构建Pyodide环境
        uses: jobovy/pyodide-buildpackage-action@v1.0.0
        with:
         pyodide-tag:0.25.0
          meta-yaml-path:'./pyodide_meta.yaml'
            matplotlib
            pillow
          output-dir: static/pyodide
      
      - name: 部署到GitHub Pages  # 保留原有部署步骤
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 部署目录包含新增的Pyodide资