name: Build Pyodide & Deploy to GitHub Pages  # 清晰体现工作流功能
on:
  push:
    branches: [main]  # 代码推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: maocs-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 新增：安装 Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build Custom Pyodide  # 构建自定义 Pyodide 环境
        uses: jobovy/pyodide-buildpackage-action@v1.0.0
        with:
          pyodide-tag: 0.25.0  # 用标签指定 Pyodide 版本，替代原版本参数
          meta-yaml-path: ./pyodide_meta.yaml  # 指向依赖配置文件
          output-dir: ./dist/static/pyodide  # 输出构建产物的目录

      - name: Deploy to GitHub Pages  # 新增部署步骤，使用正确动作
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 利用 GitHub 密钥授权部署
          publish_dir: ./dist  # 假设前端构建产物在 dist 目录，按需调整；若为根目录部署，确保内容正确且无敏感文件