name: Build Pyodide & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ''

      # 关键修改：添加ID用于输出路径
      - name: 检查 Python 版本
        id: python-info
        run: |
          python3.11 --version
          echo "path=$(which python3.11)" >> $GITHUB_OUTPUT

      # 关键修改：传递Python路径
      - name: 构建自定义 Pyodide
        uses: jobovy/pyodide-buildpackage-action@v1.0.0
        with:
          pyodide-tag: "0.25.0"
          meta-yaml-path: ./pyodide_meta.yaml
          output-dir: ./dist/static/pyodide
        env:
          PYTHON_EXECUTABLE: ${{ steps.python-info.outputs.path }}

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # 移除清理步骤（会删除构建产物）
      # - name: 清理缓存（已移除）

permissions:
  contents: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: true