name: Build Pyodide & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 使用Docker容器进行构建
      - name: 构建自定义 Pyodide
        run: |
          docker run --rm -v "$PWD":/workspace -w /workspace ubuntu:22.04 /bin/bash -c '
            # 安装构建依赖
            apt-get update && apt-get install -y \
                software-properties-common \
                build-essential \
                cmake \
                nodejs \
                npm \
                git \
                curl \
                make \
                g++
            
            # 安装Python 3.11
            add-apt-repository -y ppa:deadsnakes/ppa
            apt-get install -y python3.11 python3.11-dev python3.11-venv
            
            # 创建虚拟环境
            python3.11 -m venv /venv
            source /venv/bin/activate
            
            # 安装构建工具
            pip install pyodide-build==0.25.0
            
            # 构建Pyodide
            pyodide build --output-dir ./dist/static/pyodide --meta-yaml-path ./pyodide_meta.yaml
            
            # 修复权限问题
            chmod -R 777 ./dist
          '

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

permissions:
  contents: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: true