name: Sync main (excluding .github) to gh-pages

# 触发条件：main分支中除.github外的文件有新提交或更改时触发
on:
  push:
    branches:
      - main  # 仅监听main分支
    paths:
      - '**'                # 匹配所有文件和目录
      - '!/.github/**'      # 排除.github目录及其所有内容

jobs:
  sync-main:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 拉取main分支代码
        uses: actions/checkout@v4
        with:
          ref: main  # 明确拉取main分支
          fetch-depth: 0  # 拉取完整历史

      - name: 准备同步文件（排除.github目录）
        run: |
          # 创建临时目录用于整理待同步文件
          mkdir -p sync_dir
          
          # 复制所有文件到临时目录，同时排除.github
          rsync -av --exclude='.github' . sync_dir/
          
          # 清理临时目录中可能存在的冗余Git文件
          rm -rf sync_dir/.git

      - name: 部署到gh-pages分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sync_dir  # 推送临时目录中的内容（已排除.github）
          publish_branch: gh-pages
          force_orphan: false  # 保留gh-pages分支历史
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: "Sync from main (excluding .github): ${{ github.sha }}"

permissions:
  contents: write  # 允许写入仓库