name: Build Pyodide & Deploy to GitHub Pages  # 清晰体现工作流功能
on:
  push:
    branches: [main]  # 代码推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: macos-13  # 切换为 macOS 环境
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 利用 macOS 系统预装 Python（可能是 3.x 版本，尝试适配）
      - name: 检查系统 Python
        run: |
          python3 --version  # 看系统预装 Python 版本
          which python3     # 确认路径

      # 若系统 Python 版本不够，仍需装 3.11（但 macOS 环境预装较新，可能可跳过）
      - name: 按需安装 Python 3.11（可选，若系统版本够则注释）
        if: ${{ false }}  # 手动控制是否执行，测试时可改为 true
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build Custom Pyodide
        uses: jobovy/pyodide-buildpackage-action@v1.0.0
        with:
          pyodide-tag: 0.25.0  
          meta-yaml-path: ./pyodide_meta.yaml  
          output-dir: ./dist/static/pyodide

      # 部署步骤... # 输出构建产物的目录

      - name: Deploy to GitHub Pages  # 新增部署步骤，使用正确动作
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 利用 GitHub 密钥授权部署
          publish_dir: ./dist  # 假设前端构建产物在 dist 目录，按需调整；若为根目录部署，确保内容正确且无敏感文件