name: sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 创建部署目录
        run: |
      
          # 复制前端文件
          cp-readme.md/dist
          cp-pyodide_meta.yamd/dist
          cp-index.html dist/
          cp -r static/css dist/static/
          cp -r static/js dist/static/
          cp -r static/py dist/static/
